import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, join, basename, extname } from "path";

const assetsDir = resolve(__dirname, "../assets/email");
const outFile = resolve(__dirname, "../packages/worker/src/email/templates.ts");

const files = readdirSync(assetsDir).filter((f) => extname(f) === ".html" || extname(f) === ".txt");

const groups = new Map<string, { html?: string; txt?: string }>();
for (const file of files) {
    const base = basename(file, extname(file));
    if (!groups.has(base)) groups.set(base, {});
    const content = readFileSync(join(assetsDir, file), "utf-8");
    const escaped = content.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    if (extname(file) === ".html") groups.get(base)!.html = escaped;
    else groups.get(base)!.txt = escaped;
}

const sortedEntries = [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]));

const tsLines: string[] = [
    "// Auto-generated by scripts/bundle-templates.ts — do not edit manually",
    "",
    "const templates = {",
];

for (const [name, { html, txt }] of sortedEntries) {
    const exportName = name.replace(/-/g, "_");
    if (html) tsLines.push("  " + exportName + "_html: `" + html + "`, ");
    if (txt) tsLines.push("  " + exportName + "_txt: `" + txt + "`, ");
}

tsLines.push("} as const;", "");
tsLines.push("export type TemplateName = keyof typeof templates;", "");

const getTemplateFn = [
    "export function getTemplate(name: string): { html: string; txt: string } {",
    '  const key = name.replace(/-/g, "_");',
    '  const html = (templates as Record<string, string>)[key + "_html"];',
    '  const txt = (templates as Record<string, string>)[key + "_txt"];',
    '  if (!html || !txt) throw new Error("Template not found: " + name);',
    "  return { html, txt };",
    "}",
];
tsLines.push(...getTemplateFn, "");

tsLines.push("export function interpolate(template: string, vars: Record<string, string>): string {");
tsLines.push('  return template.replace(/{{ ?(\\w+) ?}}/gi, (_, key) => vars[key] ?? "{{ " + key + " }}");');
tsLines.push("}", "");

const templateNamesList = sortedEntries.map(([n]) => '"' + n + '"').join(", ");
tsLines.push("export const templateNames = [" + templateNamesList + "] as const;");

writeFileSync(outFile, tsLines.join("\n") + "\n", "utf-8");
console.log("Wrote " + files.length + " template files to " + outFile);
